### ISSUE TITLE
[US-EDITOR-2] As a user, I want to be able to choose a programming language so that I can code in the chosen language in the collaborative editor.

### ISSUE THREAD

**Issue by junlong4321** [CS3219-AY2223S1/cs3219-project-ay2223s1-g5#63] opened 2022-09-06 06:57 UTC
- [ ] #120

**Comment by dextertanyj** [comment] 2022-09-28 14:36
Duplicate of #120.

**Comment by dextertanyj** [comment] 2022-09-29 00:30
Duplicate of #120.

**Closed by dextertanyj** 2022-09-29 00:30 UTC
Labels: user stories, P2
